#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/fieldz
  
  bl_list_gen \
    -d ../fieldz \
    -1L  \
    -u $DVCZ_UDIR \
    -X cover \
    -X htmlcov \
    -X .ssh \
    $@
  
else
  echo "DEV_BASE is not defined"
fi
