#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/fieldz
  
  rm -rf build/* 
  
  pySloc -L py src/fieldzSpecc  -X cover -X htmlcov -X dist -X uDir -v $@
else
  echo "DEV_BASE is not defined"
fi
