#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/fieldz
  
  autopep8 -ai -r fieldz wireops
  autopep8 -ai fieldzSpecc *.py
  echo "not styling specs/ subdir"
  echo "not styling logs/ subdir"
  
else
  echo "DEV_BASE is not defined"
fi
