# projConfig.toml for fieldz

[meta]
    version = '0.1.0'

[project]
    name = 'fieldz'  # distro name
    package = 'fieldz'  # internal name
    proj_dir = '/home/jdd/dev/py/fieldz'
    main_lang = 'py'
    version = '0.11.11'
    version_date = '2017-10-24'
    author = 'Jim Dixon'
    author_email = 'jddixon@gmail.com'
    copyright = '2012-2017'
    description = 'python3 protocol for compressing/decompressing data'
    dev_status = 'alpha'
    license = 'mit'
    state = 'shared'
    url = 'https://jddixon.github.io/fieldz'

[py]
    packages=['fieldz', 'fieldz.compiler']
    package_dir = ['src']
    test_dir = ['tests']
    py_modules=[]
    scripts=['src/fieldzSpecc']
    ext_modules=[]

    # sdReq output
    distshare=['optionz', 'rnglib', 'upax_py', 'wireops', 'xlattice_py']
    env_vars=[]
    requirements=['setuptools']
    test_requirements=['big_test', 'little_big_test']
